"""AUTOGENERATED by tools/gen_queries.py — do not edit.

Regenerate with `just codegen-queries` after editing
datasette_places/sql/queries.sql.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from typing import Any


@dataclass
class PlaceList:
    id: int
    name: str
    created_by: str | None
    created_at: str
    updated_at: str
    state: str
    description: str | None


@dataclass
class PlaceCount:
    list_id: int
    cnt: Any


@dataclass
class Place:
    id: int
    list_id: int
    name: str
    address: str | None
    latitude: float
    longitude: float
    notes: str | None
    color: str | None
    metadata_json: str | None
    created_by: str | None
    created_at: str
    updated_at: str


@dataclass
class ListField:
    id: int
    list_id: int
    key: str
    label: str
    type: str
    position: int
    required: int
    is_unique: int
    config_json: str
    created_at: str
    updated_at: str


def insert_list(
    conn: sqlite3.Connection, name: str, created_by: str | None
) -> PlaceList | None:
    sql = """\
INSERT INTO _datasette_places_list (name, created_by)
VALUES ($name::text, $created_by::text::)
RETURNING id, name, created_by, created_at, updated_at, state, description;
"""
    params = {"name::text": name, "created_by::text::": created_by}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return PlaceList(*row) if row is not None else None


def select_list_by_id(conn: sqlite3.Connection, list_id: int) -> PlaceList | None:
    sql = """\
SELECT id, name, created_by, created_at, updated_at, state, description
FROM _datasette_places_list
WHERE id = $list_id::integer;
"""
    params = {"list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return PlaceList(*row) if row is not None else None


def list_lists_by_ids_and_state(
    conn: sqlite3.Connection, ids_json: str, state: str
) -> list[PlaceList]:
    sql = """\
SELECT l.id, l.name, l.created_by, l.created_at, l.updated_at, l.state, l.description
FROM _datasette_places_list l
JOIN json_each($ids_json::text) je ON je.value = l.id
WHERE l.state = $state::text
ORDER BY l.updated_at DESC;
"""
    params = {"ids_json::text": ids_json, "state::text": state}
    cursor = conn.execute(sql, params)
    return [PlaceList(*row) for row in cursor.fetchall()]


def update_list_name(
    conn: sqlite3.Connection, name: str, list_id: int
) -> PlaceList | None:
    sql = """\
UPDATE _datasette_places_list
SET name = $name::text,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $list_id::integer
RETURNING id, name, created_by, created_at, updated_at, state, description;
"""
    params = {"name::text": name, "list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return PlaceList(*row) if row is not None else None


def update_list_description(
    conn: sqlite3.Connection, description: str | None, list_id: int
) -> PlaceList | None:
    sql = """\
UPDATE _datasette_places_list
SET description = $description::text::,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $list_id::integer
RETURNING id, name, created_by, created_at, updated_at, state, description;
"""
    params = {"description::text::": description, "list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return PlaceList(*row) if row is not None else None


def trash_list(conn: sqlite3.Connection, list_id: int) -> None:
    sql = """\
UPDATE _datasette_places_list
SET state = 'trashed',
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $list_id::integer;
"""
    params = {"list_id::integer": list_id}
    conn.execute(sql, params)
    return None


def restore_list(conn: sqlite3.Connection, list_id: int) -> None:
    sql = """\
UPDATE _datasette_places_list
SET state = 'active',
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $list_id::integer;
"""
    params = {"list_id::integer": list_id}
    conn.execute(sql, params)
    return None


def bump_list_updated_at(conn: sqlite3.Connection, list_id: int) -> None:
    sql = """\
UPDATE _datasette_places_list
SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $list_id::integer;
"""
    params = {"list_id::integer": list_id}
    conn.execute(sql, params)
    return None


def place_count_for_list(conn: sqlite3.Connection, list_id: int) -> Any | None:
    sql = "SELECT COUNT(*) FROM _datasette_places_place WHERE list_id = $list_id::integer;"
    params = {"list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def place_counts_by_list_ids(
    conn: sqlite3.Connection, ids_json: str
) -> list[PlaceCount]:
    sql = """\
SELECT list_id, COUNT(*) AS cnt
FROM _datasette_places_place
WHERE list_id IN (SELECT CAST(value AS INTEGER) FROM json_each($ids_json::text))
GROUP BY list_id;
"""
    params = {"ids_json::text": ids_json}
    cursor = conn.execute(sql, params)
    return [PlaceCount(*row) for row in cursor.fetchall()]


def insert_place(
    conn: sqlite3.Connection,
    list_id: int,
    name: str,
    address: str | None,
    latitude: float,
    longitude: float,
    notes: str | None,
    color: str | None,
    metadata_json: str | None,
    created_by: str | None,
) -> Place | None:
    sql = """\
INSERT INTO _datasette_places_place
    (list_id, name, address, latitude, longitude, notes, color, metadata_json, created_by)
VALUES
    ($list_id::integer, $name::text, $address::text::, $latitude::real, $longitude::real,
     $notes::text::, $color::text::, $metadata_json::text::, $created_by::text::)
RETURNING id, list_id, name, address, latitude, longitude, notes, color, metadata_json, created_by, created_at, updated_at;
"""
    params = {
        "list_id::integer": list_id,
        "name::text": name,
        "address::text::": address,
        "latitude::real": latitude,
        "longitude::real": longitude,
        "notes::text::": notes,
        "color::text::": color,
        "metadata_json::text::": metadata_json,
        "created_by::text::": created_by,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Place(*row) if row is not None else None


def select_places_for_list(conn: sqlite3.Connection, list_id: int) -> list[Place]:
    sql = """\
SELECT id, list_id, name, address, latitude, longitude, notes, color, metadata_json, created_by, created_at, updated_at
FROM _datasette_places_place
WHERE list_id = $list_id::integer
ORDER BY created_at ASC;
"""
    params = {"list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    return [Place(*row) for row in cursor.fetchall()]


def select_place_by_id(conn: sqlite3.Connection, place_id: int) -> Place | None:
    sql = """\
SELECT id, list_id, name, address, latitude, longitude, notes, color, metadata_json, created_by, created_at, updated_at
FROM _datasette_places_place
WHERE id = $place_id::integer;
"""
    params = {"place_id::integer": place_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Place(*row) if row is not None else None


def select_place_list_id(conn: sqlite3.Connection, place_id: int) -> int | None:
    sql = "SELECT list_id FROM _datasette_places_place WHERE id = $place_id::integer;"
    params = {"place_id::integer": place_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def update_place(
    conn: sqlite3.Connection,
    name: str,
    address: str | None,
    latitude: float,
    longitude: float,
    notes: str | None,
    color: str | None,
    metadata_json: str | None,
    place_id: int,
) -> Place | None:
    sql = """\
UPDATE _datasette_places_place
SET name = $name::text,
    address = $address::text::,
    latitude = $latitude::real,
    longitude = $longitude::real,
    notes = $notes::text::,
    color = $color::text::,
    metadata_json = $metadata_json::text::,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $place_id::integer
RETURNING id, list_id, name, address, latitude, longitude, notes, color, metadata_json, created_by, created_at, updated_at;
"""
    params = {
        "name::text": name,
        "address::text::": address,
        "latitude::real": latitude,
        "longitude::real": longitude,
        "notes::text::": notes,
        "color::text::": color,
        "metadata_json::text::": metadata_json,
        "place_id::integer": place_id,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Place(*row) if row is not None else None


def delete_place(conn: sqlite3.Connection, place_id: int) -> None:
    sql = "DELETE FROM _datasette_places_place WHERE id = $place_id::integer;"
    params = {"place_id::integer": place_id}
    conn.execute(sql, params)
    return None


def insert_list_field(
    conn: sqlite3.Connection,
    list_id: int,
    key: str,
    label: str,
    type: str,
    position: int,
    required: int,
    is_unique: int,
    config_json: str,
) -> ListField | None:
    sql = """\
INSERT INTO _datasette_places_list_field
    (list_id, key, label, type, position, required, is_unique, config_json)
VALUES
    ($list_id::integer, $key::text, $label::text, $type::text, $position::integer,
     $required::integer, $is_unique::integer, $config_json::text)
RETURNING id, list_id, key, label, type, position, required, is_unique, config_json, created_at, updated_at;
"""
    params = {
        "list_id::integer": list_id,
        "key::text": key,
        "label::text": label,
        "type::text": type,
        "position::integer": position,
        "required::integer": required,
        "is_unique::integer": is_unique,
        "config_json::text": config_json,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return ListField(*row) if row is not None else None


def select_fields_for_list(conn: sqlite3.Connection, list_id: int) -> list[ListField]:
    sql = """\
SELECT id, list_id, key, label, type, position, required, is_unique, config_json, created_at, updated_at
FROM _datasette_places_list_field
WHERE list_id = $list_id::integer
ORDER BY position ASC, id ASC;
"""
    params = {"list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    return [ListField(*row) for row in cursor.fetchall()]


def select_list_field_by_id(
    conn: sqlite3.Connection, field_id: int
) -> ListField | None:
    sql = """\
SELECT id, list_id, key, label, type, position, required, is_unique, config_json, created_at, updated_at
FROM _datasette_places_list_field
WHERE id = $field_id::integer;
"""
    params = {"field_id::integer": field_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return ListField(*row) if row is not None else None


def max_field_position_for_list(conn: sqlite3.Connection, list_id: int) -> Any | None:
    sql = """\
SELECT COALESCE(MAX(position), -1) FROM _datasette_places_list_field
WHERE list_id = $list_id::integer;
"""
    params = {"list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def update_list_field(
    conn: sqlite3.Connection,
    label: str,
    type: str,
    position: int,
    required: int,
    is_unique: int,
    config_json: str,
    field_id: int,
) -> ListField | None:
    sql = """\
UPDATE _datasette_places_list_field
SET label = $label::text,
    type = $type::text,
    position = $position::integer,
    required = $required::integer,
    is_unique = $is_unique::integer,
    config_json = $config_json::text,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $field_id::integer
RETURNING id, list_id, key, label, type, position, required, is_unique, config_json, created_at, updated_at;
"""
    params = {
        "label::text": label,
        "type::text": type,
        "position::integer": position,
        "required::integer": required,
        "is_unique::integer": is_unique,
        "config_json::text": config_json,
        "field_id::integer": field_id,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return ListField(*row) if row is not None else None


def delete_list_field(conn: sqlite3.Connection, field_id: int) -> None:
    sql = "DELETE FROM _datasette_places_list_field WHERE id = $field_id::integer;"
    params = {"field_id::integer": field_id}
    conn.execute(sql, params)
    return None


def set_place_metadata_key(
    conn: sqlite3.Connection, key: str, value_json: str, place_id: int
) -> Place | None:
    sql = """\
UPDATE _datasette_places_place
SET metadata_json = json_set(COALESCE(metadata_json, '{}'), '$.' || $key::text, json($value_json::text)),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $place_id::integer
RETURNING id, list_id, name, address, latitude, longitude, notes, color, metadata_json, created_by, created_at, updated_at;
"""
    params = {
        "key::text": key,
        "value_json::text": value_json,
        "place_id::integer": place_id,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Place(*row) if row is not None else None


def remove_place_metadata_key(
    conn: sqlite3.Connection, key: str, place_id: int
) -> Place | None:
    sql = """\
UPDATE _datasette_places_place
SET metadata_json = json_remove(COALESCE(metadata_json, '{}'), '$.' || $key::text),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $place_id::integer
RETURNING id, list_id, name, address, latitude, longitude, notes, color, metadata_json, created_by, created_at, updated_at;
"""
    params = {"key::text": key, "place_id::integer": place_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Place(*row) if row is not None else None
