"""AUTOGENERATED by tools/gen_queries.py — do not edit.

Regenerate with `just codegen-queries` after editing
datasette_places/sql/queries.sql.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from typing import Any


@dataclass
class PlaceList:
    id: int
    name: str
    created_by: str | None
    created_at: str
    updated_at: str
    state: str
    description: str | None


@dataclass
class PlaceCount:
    list_id: int
    cnt: Any


@dataclass
class Place:
    id: int
    list_id: int
    name: str
    address: str | None
    latitude: float
    longitude: float
    notes: str | None
    color: str | None
    metadata_json: str | None
    created_by: str | None
    created_at: str
    updated_at: str


@dataclass
class Geocoder:
    id: str
    provider_type: str
    label: str
    config_json: str
    enabled: int
    created_by: str | None
    created_at: str
    updated_at: str


@dataclass
class ListGeocoder:
    list_id: int
    geocoder_id: str
    enabled: int
    is_default: int
    position: int
    added_by: str | None
    added_at: str


@dataclass
class ListGeocoderRow:
    list_id: int
    geocoder_id: str
    enabled: int
    is_default: int
    position: int
    provider_type: str
    label: str
    config_json: str
    geocoder_enabled: int


def insert_list(
    conn: sqlite3.Connection, name: str, created_by: str | None
) -> PlaceList | None:
    sql = """\
INSERT INTO _datasette_places_list (name, created_by)
VALUES ($name::text, $created_by::text::)
RETURNING id, name, created_by, created_at, updated_at, state, description;
"""
    params = {"name::text": name, "created_by::text::": created_by}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return PlaceList(*row) if row is not None else None


def select_list_by_id(conn: sqlite3.Connection, list_id: int) -> PlaceList | None:
    sql = """\
SELECT id, name, created_by, created_at, updated_at, state, description
FROM _datasette_places_list
WHERE id = $list_id::integer;
"""
    params = {"list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return PlaceList(*row) if row is not None else None


def list_lists_by_ids_and_state(
    conn: sqlite3.Connection, ids_json: str, state: str
) -> list[PlaceList]:
    sql = """\
SELECT l.id, l.name, l.created_by, l.created_at, l.updated_at, l.state, l.description
FROM _datasette_places_list l
JOIN json_each($ids_json::text) je ON je.value = l.id
WHERE l.state = $state::text
ORDER BY l.updated_at DESC;
"""
    params = {"ids_json::text": ids_json, "state::text": state}
    cursor = conn.execute(sql, params)
    return [PlaceList(*row) for row in cursor.fetchall()]


def update_list_name(
    conn: sqlite3.Connection, name: str, list_id: int
) -> PlaceList | None:
    sql = """\
UPDATE _datasette_places_list
SET name = $name::text,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $list_id::integer
RETURNING id, name, created_by, created_at, updated_at, state, description;
"""
    params = {"name::text": name, "list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return PlaceList(*row) if row is not None else None


def update_list_description(
    conn: sqlite3.Connection, description: str | None, list_id: int
) -> PlaceList | None:
    sql = """\
UPDATE _datasette_places_list
SET description = $description::text::,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $list_id::integer
RETURNING id, name, created_by, created_at, updated_at, state, description;
"""
    params = {"description::text::": description, "list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return PlaceList(*row) if row is not None else None


def trash_list(conn: sqlite3.Connection, list_id: int) -> None:
    sql = """\
UPDATE _datasette_places_list
SET state = 'trashed',
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $list_id::integer;
"""
    params = {"list_id::integer": list_id}
    conn.execute(sql, params)
    return None


def restore_list(conn: sqlite3.Connection, list_id: int) -> None:
    sql = """\
UPDATE _datasette_places_list
SET state = 'active',
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $list_id::integer;
"""
    params = {"list_id::integer": list_id}
    conn.execute(sql, params)
    return None


def bump_list_updated_at(conn: sqlite3.Connection, list_id: int) -> None:
    sql = """\
UPDATE _datasette_places_list
SET updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $list_id::integer;
"""
    params = {"list_id::integer": list_id}
    conn.execute(sql, params)
    return None


def place_count_for_list(conn: sqlite3.Connection, list_id: int) -> Any | None:
    sql = "SELECT COUNT(*) FROM _datasette_places_place WHERE list_id = $list_id::integer;"
    params = {"list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def place_counts_by_list_ids(
    conn: sqlite3.Connection, ids_json: str
) -> list[PlaceCount]:
    sql = """\
SELECT list_id, COUNT(*) AS cnt
FROM _datasette_places_place
WHERE list_id IN (SELECT CAST(value AS INTEGER) FROM json_each($ids_json::text))
GROUP BY list_id;
"""
    params = {"ids_json::text": ids_json}
    cursor = conn.execute(sql, params)
    return [PlaceCount(*row) for row in cursor.fetchall()]


def insert_place(
    conn: sqlite3.Connection,
    list_id: int,
    name: str,
    address: str | None,
    latitude: float,
    longitude: float,
    notes: str | None,
    color: str | None,
    metadata_json: str | None,
    created_by: str | None,
) -> Place | None:
    sql = """\
INSERT INTO _datasette_places_place
    (list_id, name, address, latitude, longitude, notes, color, metadata_json, created_by)
VALUES
    ($list_id::integer, $name::text, $address::text::, $latitude::real, $longitude::real,
     $notes::text::, $color::text::, $metadata_json::text::, $created_by::text::)
RETURNING id, list_id, name, address, latitude, longitude, notes, color, metadata_json, created_by, created_at, updated_at;
"""
    params = {
        "list_id::integer": list_id,
        "name::text": name,
        "address::text::": address,
        "latitude::real": latitude,
        "longitude::real": longitude,
        "notes::text::": notes,
        "color::text::": color,
        "metadata_json::text::": metadata_json,
        "created_by::text::": created_by,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Place(*row) if row is not None else None


def select_places_for_list(conn: sqlite3.Connection, list_id: int) -> list[Place]:
    sql = """\
SELECT id, list_id, name, address, latitude, longitude, notes, color, metadata_json, created_by, created_at, updated_at
FROM _datasette_places_place
WHERE list_id = $list_id::integer
ORDER BY created_at ASC;
"""
    params = {"list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    return [Place(*row) for row in cursor.fetchall()]


def select_place_by_id(conn: sqlite3.Connection, place_id: int) -> Place | None:
    sql = """\
SELECT id, list_id, name, address, latitude, longitude, notes, color, metadata_json, created_by, created_at, updated_at
FROM _datasette_places_place
WHERE id = $place_id::integer;
"""
    params = {"place_id::integer": place_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Place(*row) if row is not None else None


def select_place_list_id(conn: sqlite3.Connection, place_id: int) -> int | None:
    sql = "SELECT list_id FROM _datasette_places_place WHERE id = $place_id::integer;"
    params = {"place_id::integer": place_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def update_place(
    conn: sqlite3.Connection,
    name: str,
    address: str | None,
    latitude: float,
    longitude: float,
    notes: str | None,
    color: str | None,
    metadata_json: str | None,
    place_id: int,
) -> Place | None:
    sql = """\
UPDATE _datasette_places_place
SET name = $name::text,
    address = $address::text::,
    latitude = $latitude::real,
    longitude = $longitude::real,
    notes = $notes::text::,
    color = $color::text::,
    metadata_json = $metadata_json::text::,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $place_id::integer
RETURNING id, list_id, name, address, latitude, longitude, notes, color, metadata_json, created_by, created_at, updated_at;
"""
    params = {
        "name::text": name,
        "address::text::": address,
        "latitude::real": latitude,
        "longitude::real": longitude,
        "notes::text::": notes,
        "color::text::": color,
        "metadata_json::text::": metadata_json,
        "place_id::integer": place_id,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Place(*row) if row is not None else None


def delete_place(conn: sqlite3.Connection, place_id: int) -> None:
    sql = "DELETE FROM _datasette_places_place WHERE id = $place_id::integer;"
    params = {"place_id::integer": place_id}
    conn.execute(sql, params)
    return None


def insert_geocoder(
    conn: sqlite3.Connection,
    id: str,
    provider_type: str,
    label: str,
    config_json: str,
    enabled: int,
    created_by: str | None,
) -> Geocoder | None:
    sql = """\
INSERT INTO _datasette_places_geocoder (id, provider_type, label, config_json, enabled, created_by)
VALUES ($id::text, $provider_type::text, $label::text, $config_json::text, $enabled::integer, $created_by::text::)
RETURNING id, provider_type, label, config_json, enabled, created_by, created_at, updated_at;
"""
    params = {
        "id::text": id,
        "provider_type::text": provider_type,
        "label::text": label,
        "config_json::text": config_json,
        "enabled::integer": enabled,
        "created_by::text::": created_by,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Geocoder(*row) if row is not None else None


def select_geocoder_by_id(conn: sqlite3.Connection, id: str) -> Geocoder | None:
    sql = """\
SELECT id, provider_type, label, config_json, enabled, created_by, created_at, updated_at
FROM _datasette_places_geocoder
WHERE id = $id::text;
"""
    params = {"id::text": id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Geocoder(*row) if row is not None else None


def list_geocoders(conn: sqlite3.Connection) -> list[Geocoder]:
    sql = """\
SELECT id, provider_type, label, config_json, enabled, created_by, created_at, updated_at
FROM _datasette_places_geocoder
ORDER BY label COLLATE NOCASE ASC;
"""
    params: dict[str, Any] = {}
    cursor = conn.execute(sql, params)
    return [Geocoder(*row) for row in cursor.fetchall()]


def list_geocoders_by_ids(conn: sqlite3.Connection, ids_json: str) -> list[Geocoder]:
    sql = """\
SELECT g.id, g.provider_type, g.label, g.config_json, g.enabled, g.created_by, g.created_at, g.updated_at
FROM _datasette_places_geocoder g
JOIN json_each($ids_json::text) je ON je.value = g.id
ORDER BY g.label COLLATE NOCASE ASC;
"""
    params = {"ids_json::text": ids_json}
    cursor = conn.execute(sql, params)
    return [Geocoder(*row) for row in cursor.fetchall()]


def update_geocoder(
    conn: sqlite3.Connection, label: str, config_json: str, enabled: int, id: str
) -> Geocoder | None:
    sql = """\
UPDATE _datasette_places_geocoder
SET label = $label::text,
    config_json = $config_json::text,
    enabled = $enabled::integer,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = $id::text
RETURNING id, provider_type, label, config_json, enabled, created_by, created_at, updated_at;
"""
    params = {
        "label::text": label,
        "config_json::text": config_json,
        "enabled::integer": enabled,
        "id::text": id,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return Geocoder(*row) if row is not None else None


def delete_geocoder(conn: sqlite3.Connection, id: str) -> None:
    sql = "DELETE FROM _datasette_places_geocoder WHERE id = $id::text;"
    params = {"id::text": id}
    conn.execute(sql, params)
    return None


def attach_geocoder_to_list(
    conn: sqlite3.Connection, list_id: int, geocoder_id: str, added_by: str | None
) -> ListGeocoder | None:
    sql = """\
INSERT INTO _datasette_places_list_geocoder (list_id, geocoder_id, enabled, is_default, position, added_by)
VALUES ($list_id::integer, $geocoder_id::text, 1, 0,
        (SELECT COALESCE(MAX(position), -1) + 1 FROM _datasette_places_list_geocoder WHERE list_id = $list_id::integer),
        $added_by::text::)
ON CONFLICT (list_id, geocoder_id) DO UPDATE SET enabled = 1
RETURNING list_id, geocoder_id, enabled, is_default, position, added_by, added_at;
"""
    params = {
        "list_id::integer": list_id,
        "geocoder_id::text": geocoder_id,
        "added_by::text::": added_by,
    }
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return ListGeocoder(*row) if row is not None else None


def select_list_geocoder(
    conn: sqlite3.Connection, list_id: int, geocoder_id: str
) -> ListGeocoder | None:
    sql = """\
SELECT list_id, geocoder_id, enabled, is_default, position, added_by, added_at
FROM _datasette_places_list_geocoder
WHERE list_id = $list_id::integer AND geocoder_id = $geocoder_id::text;
"""
    params = {"list_id::integer": list_id, "geocoder_id::text": geocoder_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return ListGeocoder(*row) if row is not None else None


def list_geocoders_for_list(
    conn: sqlite3.Connection, list_id: int
) -> list[ListGeocoderRow]:
    sql = """\
SELECT lg.list_id, lg.geocoder_id, lg.enabled, lg.is_default, lg.position,
       g.provider_type, g.label, g.config_json, g.enabled AS geocoder_enabled
FROM _datasette_places_list_geocoder lg
JOIN _datasette_places_geocoder g ON g.id = lg.geocoder_id
WHERE lg.list_id = $list_id::integer
ORDER BY lg.position ASC, g.label COLLATE NOCASE ASC;
"""
    params = {"list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    return [ListGeocoderRow(*row) for row in cursor.fetchall()]


def default_geocoder_for_list(conn: sqlite3.Connection, list_id: int) -> str | None:
    sql = """\
SELECT geocoder_id
FROM _datasette_places_list_geocoder
WHERE list_id = $list_id::integer AND is_default = 1 AND enabled = 1
LIMIT 1;
"""
    params = {"list_id::integer": list_id}
    cursor = conn.execute(sql, params)
    row = cursor.fetchone()
    return row[0] if row is not None else None


def set_list_geocoder_enabled(
    conn: sqlite3.Connection, enabled: int, list_id: int, geocoder_id: str
) -> None:
    sql = """\
UPDATE _datasette_places_list_geocoder
SET enabled = $enabled::integer
WHERE list_id = $list_id::integer AND geocoder_id = $geocoder_id::text;
"""
    params = {
        "enabled::integer": enabled,
        "list_id::integer": list_id,
        "geocoder_id::text": geocoder_id,
    }
    conn.execute(sql, params)
    return None


def clear_list_geocoder_default(conn: sqlite3.Connection, list_id: int) -> None:
    sql = """\
UPDATE _datasette_places_list_geocoder
SET is_default = 0
WHERE list_id = $list_id::integer;
"""
    params = {"list_id::integer": list_id}
    conn.execute(sql, params)
    return None


def set_list_geocoder_default(
    conn: sqlite3.Connection, list_id: int, geocoder_id: str
) -> None:
    sql = """\
UPDATE _datasette_places_list_geocoder
SET is_default = 1
WHERE list_id = $list_id::integer AND geocoder_id = $geocoder_id::text;
"""
    params = {"list_id::integer": list_id, "geocoder_id::text": geocoder_id}
    conn.execute(sql, params)
    return None


def detach_geocoder_from_list(
    conn: sqlite3.Connection, list_id: int, geocoder_id: str
) -> None:
    sql = """\
DELETE FROM _datasette_places_list_geocoder
WHERE list_id = $list_id::integer AND geocoder_id = $geocoder_id::text;
"""
    params = {"list_id::integer": list_id, "geocoder_id::text": geocoder_id}
    conn.execute(sql, params)
    return None
