[project]
name = "datasette-places"
version = "0.0.1a2"
description = "Datasette plugin for creating and sharing lists of places on a map"
readme = "README.md"
license = "Apache-2.0"
classifiers = [
    "Framework :: Datasette"
]
requires-python = ">=3.10"
dependencies = [
    "datasette>1a",
    "datasette-plugin-router>=0.0.1a3",
    "datasette-vite>=0.0.1a4",
    "sqlite-migrate>=0.1b0",
    "sqlite-utils>=3.38",
    "httpx>=0.27",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "ruff>=0.15.0",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.entry-points.datasette]
places = "datasette_places"

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

[tool.setuptools.packages.find]
include = ["datasette_places*"]

[tool.setuptools.package-data]
datasette_places = ["static/**/*", "templates/**/*", "manifest.json"]
